version: "3.8"

services:

  config-server:
    image: joydeepchowdhury/config-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - my-network
     
  eureka-discovery-server:
    image: joydeepchowdhury/eureka-discovery-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - my-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      
  cloud-gateway-server:
    image: joydeepchowdhury/cloud-gateway-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - my-network
    depends_on:
      - config-server
      - eureka-discovery-server
      - loans-microservice
      - cards-microservice
      - accounts-microservice
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/    
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery-server:8070/eureka/
      
  accounts-microservice:
    image: joydeepchowdhury/accounts-microservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - config-server
      - eureka-discovery-server
      - loans-microservice
      - cards-microservice
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery-server:8070/eureka/
      
  accounts-microservice-second:
    image: joydeepchowdhury/accounts-microservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8081:8080"
    networks:
      - my-network
    depends_on:
      - config-server
      - eureka-discovery-server
      - loans-microservice
      - cards-microservice
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery-server:8070/eureka/
  
  loans-microservice:
    image: joydeepchowdhury/loans-microservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - my-network
    depends_on:
      - config-server
      - eureka-discovery-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery-server:8070/eureka/
    
  cards-microservice:
    image: joydeepchowdhury/cards-microservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - my-network
    depends_on:
      - config-server
      - eureka-discovery-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery-server:8070/eureka/
      
networks:
  my-network: